/* confdefs.h */
#define PACKAGE_NAME "ViennaRNA"
#define PACKAGE_TARNAME "ViennaRNA"
#define PACKAGE_VERSION "2.4.14"
#define PACKAGE_STRING "ViennaRNA 2.4.14"
#define PACKAGE_BUGREPORT "rna@tbi.univie.ac.at"
#define PACKAGE_URL "http://www.tbi.univie.ac.at/RNA"
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define __EXTENSIONS__ 1
#define _ALL_SOURCE 1
#define _GNU_SOURCE 1
#define _POSIX_PTHREAD_SEMANTICS 1
#define _TANDEM_SOURCE 1
#define PACKAGE "ViennaRNA"
#define VERSION "2.4.14"
#define UNUSED __attribute__ ((unused))
#define HAVE_DLFCN_H 1
#define LT_OBJDIR ".libs/"
#define HAVE_LIBM 1
#define STDC_HEADERS 1
#define HAVE__BOOL 1
#define HAVE_STDBOOL_H 1
#define HAVE_MALLOC_H 1
#define HAVE_FLOAT_H 1
#define HAVE_LIMITS_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_STRINGS_H 1
#define HAVE_UNISTD_H 1
#define HAVE_MATH_H 1
#define HAVE_STDARG_H 1
#define HAVE_STDLIB_H 1
#define HAVE_MALLOC 1
#define HAVE_STDLIB_H 1
#define HAVE_REALLOC 1
#define HAVE_FLOOR 1
#define HAVE_STRDUP 1
#define HAVE_STRSTR 1
#define HAVE_STRCHR 1
#define HAVE_STRRCHR 1
#define HAVE_STRSTR 1
#define HAVE_STRTOL 1
#define HAVE_STRTOUL 1
#define HAVE_POW 1
#define HAVE_RINT 1
#define HAVE_SQRT 1
#define HAVE_ERAND48 1
#define HAVE_MEMSET 1
#define HAVE_MEMMOVE 1
#define HAVE_ERAND48 1
#define HAVE_ASPRINTF 1
#define HAVE_VASPRINTF 1
#define VRNA_WITH_SVM 1
#define VRNA_WITH_JSON_SUPPORT 1
#define HAVE_OPENMP 1
#define HAVE_OPENMP 1
#define HAVE_PTHREAD_PRIO_INHERIT 1
#define VRNA_WITH_PTHREADS 1
#define VRNA_WITH_BOUSTROPHEDON 1
#define VRNA_WITH_SIMD_SSE41 1
#define WITH_PERL_INTERFACE 1
#define WITH_PYTHON2_INTERFACE 1
